# -*- coding: utf-8 -*-
"""histo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNvXGHcfdknNekvY1UZX_Izelr08YPw3
"""

!git clone https://git_token@github.com/username/repository.git

'''python from google.colab import drive
drive.mount('/content/drive')'''

import pandas as pd
df=pd.read_csv('/content/Dataset .csv')
Dataset=pd.read_csv('/content/Dataset .csv')

df.head()

"""#price range Analysis
Determine the most common  price range among all the restaurants.

"""

import statistics

"""Mode is the value that appears most frequently in a dataset.it is identifying the most common element"""

statistics.mode(Dataset['Price range'])

"""calculate the average rating for each price range"""

statistics.mean(Dataset['Price range'])

"""Identify the colour that represents the highest average rating among different price ranges"""

df['Price range'].max()

"""The colour that represent the highest average rating among the price range

colour: Green

Table Booking And Online delivery

% of table booking
"""

Dataset = Dataset
Dataset.head()

len(Dataset)

"""calculate the (percentage)%  of online  delivery  and table booking"""

num_rows = len(df)
print("Number of rows:", num_rows)



"""# Calculate sum of table booking"""

total_sum = df.sum(numeric_only=True)
print(total_sum)

"""FEATURE ENGINEERING (LEVEL 2)"""

df.head()





